/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-01-21 03:01:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class indexAdmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1672774626605L));
    _jspx_dependants.put("jar:file:/C:/Users/Rodolfo%20Andre/Desktop/Test_2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/app/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1668791496000L));
    _jspx_dependants.put("/snippets/navAdmin.jsp", Long.valueOf(1674190708450L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("	<link rel=\"icon\" type=\"image/png\" href=\"./img/icono.jpg\" sizes=\"32x32\"/>\r\n");
      out.write("	<title>Configuración</title>\r\n");
      out.write("	\r\n");
      out.write("	<!--GOOGLE FONTS - RALEWAY-->\r\n");
      out.write("	<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("	<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("	<link href=\"https://fonts.googleapis.com/css2?family=Chau+Philomene+One&family=Raleway:wght@500&family=Secular+One&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("	\r\n");
      out.write("	<!--BOOTSTRAP CSS-->\r\n");
      out.write("	<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD\" crossorigin=\"anonymous\">\r\n");
      out.write("	\r\n");
      out.write("	<!--BOOTSTRAP ICONS-->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css\">	\r\n");
      out.write("	\r\n");
      out.write("	<!--CUSTOM CSS-->\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"./css/style.css\">\r\n");
      out.write("	\r\n");
      out.write("	<!--SCRIPTS-->\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"d-flex min-vh-100\">\r\n");
      out.write("		");
      out.write("<div class=\"d-flex flex-column shadow\" style=\"width: 280px; background-color: #FAE6C5;\">\r\n");
      out.write("	<a href=\"indexUser.jsp\" style=\"border-bottom: 1px solid #FAE6C5;\">\r\n");
      out.write("		<img src=\"./img/cartel.jpg\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("	</a>\r\n");
      out.write("\r\n");
      out.write("	<ul class=\"nav flex-column mb-auto\">\r\n");
      out.write("		<li>\r\n");
      out.write("			<a href=\"indexAdmin.jsp\" class=\"btn-home\"> \r\n");
      out.write("				<i class=\"bi bi-house-door-fill fs-4\"></i>\r\n");
      out.write("                 \r\n");
      out.write("                 <span class=\"fs-5 fw-semibold\">Inicio</span>\r\n");
      out.write("			</a>\r\n");
      out.write("		</li>\r\n");
      out.write("\r\n");
      out.write("		<li class=\"nav-item\">\r\n");
      out.write("			<a href=\"#\" class=\"nav-link link-dark\" data-bs-toggle=\"collapse\" aria-expanded=\"true\" aria-controls=\"menu\" data-bs-target=\"#menu\">\r\n");
      out.write("				<i class=\"bi bi-journals fs-4\"></i>\r\n");
      out.write("	           	\r\n");
      out.write("	           	<span class=\"fs-5 fw-semibold \">Pedidos</span>\r\n");
      out.write("			</a> \r\n");
      out.write("		\r\n");
      out.write("			<!--desplegable Comandas-->\r\n");
      out.write("			<div class=\"collapse\" id=\"menu\">\r\n");
      out.write("				<ul class=\"ms-3 pb-1 list-unstyled\">\r\n");
      out.write("					<li class=\"nav-item\">\r\n");
      out.write("						<a href=\"PedidosController?type=listarPedidos&p=1\" class=\"nav-link link-dark\"> \r\n");
      out.write("							<i class=\"bi bi-receipt-cutoff fs-4\"></i>\r\n");
      out.write("                           	\r\n");
      out.write("                           	<span class=\"fw-semibold\">Actualizar pedidos</span>   	\r\n");
      out.write("                       	</a>\r\n");
      out.write("                   	</li>\r\n");
      out.write("\r\n");
      out.write("					<li class=\"nav-item\">\r\n");
      out.write("						<a href=\"HojaEnvioController?p=1\" class=\"nav-link link-dark\"> \r\n");
      out.write("							<i class=\"bi bi-search fs-4\"></i>\r\n");
      out.write("                           	\r\n");
      out.write("                           	<span class=\"fw-semibold\">Actualizar Hoja de envío</span>\r\n");
      out.write("						</a>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</li>\r\n");
      out.write("\r\n");
      out.write("		<li>\r\n");
      out.write("			<a href=\"CajaController?p=1\" class=\"nav-link link-dark\">\r\n");
      out.write("				<i class=\"bi bi-cash-coin fs-4\"></i>\r\n");
      out.write("               	\r\n");
      out.write("               	<span class=\"fs-5 fw-semibold\">Caja Registradora</span>\r\n");
      out.write("			</a>\r\n");
      out.write("		</li>\r\n");
      out.write("\r\n");
      out.write("		<li>\r\n");
      out.write("			<a href=\"#\" class=\" nav-link link-dark\" data-bs-toggle=\"collapse\" aria-expanded=\"true\" aria-controls=\"menuConfiguracion\" data-bs-target=\"#menuConfiguracion\"> \r\n");
      out.write("				<i class=\"bi bi-wrench-adjustable-circle fs-4\"></i>\r\n");
      out.write("                \r\n");
      out.write("               	<span class=\"fs-5 fw-semibold\">Configuración</span>\r\n");
      out.write("			</a>\r\n");
      out.write("			 \r\n");
      out.write("			<!--desplegable Configuración-->\r\n");
      out.write("			<div class=\"collapse\" id=\"menuConfiguracion\">\r\n");
      out.write("				<ul class=\"ms-3 pb-1 list-unstyled\">\r\n");
      out.write("					<li class=\"nav-item\">\r\n");
      out.write("						<a href=\"EmpleadosController?p=1\" class=\"nav-link link-dark\">\r\n");
      out.write("							<i class=\"bi bi-people-fill fs-4\"></i>\r\n");
      out.write("                            \r\n");
      out.write("                            <span class=\"fw-semibold\">Configurar Empleados</span>\r\n");
      out.write("						</a>\r\n");
      out.write("					</li>\r\n");
      out.write("\r\n");
      out.write("					<li class=\"nav-item \">\r\n");
      out.write("						<a href=\"ProductosController?pProductos=1\" class=\"nav-link link-dark\"> \r\n");
      out.write("							<i class=\"bi bi-egg-fried fs-4\"></i>\r\n");
      out.write("                           	\r\n");
      out.write("                           	<span class=\"fw-semibold\">Configurar Productos</span>\r\n");
      out.write("						</a>\r\n");
      out.write("					</li>\r\n");
      out.write("\r\n");
      out.write("					<li class=\"nav-item\">\r\n");
      out.write("						<a href=\"PromocionesController?p=1\" class=\"nav-link link-dark\"> \r\n");
      out.write("							<i class=\"bi bi-cup-hot-fill fs-4\"></i>\r\n");
      out.write("                    		\r\n");
      out.write("                    		<span class=\"fw-semibold\">Configurar Promociones</span>\r\n");
      out.write("						</a>\r\n");
      out.write("					</li>\r\n");
      out.write("\r\n");
      out.write("					<li class=\"nav-item\">\r\n");
      out.write("						<a href=\"ZonaDeRepartoController?p=1\" class=\"nav-link link-dark\">\r\n");
      out.write("							<i class=\"bi bi-geo-alt-fill fs-4\"></i>\r\n");
      out.write("							\r\n");
      out.write("							<span class=\"fw-semibold\">Configurar zona de repartición</span>\r\n");
      out.write("						</a>\r\n");
      out.write("					</li>\r\n");
      out.write("					\r\n");
      out.write("					<li class=\"nav-item\">\r\n");
      out.write("						<a href=\"Establecimiento?type=listarinfo\" class=\"nav-link link-dark\">\r\n");
      out.write("							<i class=\"bi bi-bank fs-4\"></i>\r\n");
      out.write("							\r\n");
      out.write("							<span class=\"fw-semibold\">Configurar establecimiento</span>\r\n");
      out.write("						</a>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</li>\r\n");
      out.write("		\r\n");
      out.write("		<li class=\"nav-item\">\r\n");
      out.write("			<a href=\"#\" class=\"nav-link link-dark\" data-bs-toggle=\"collapse\" aria-expanded=\"true\" aria-controls=\"reporte\" data-bs-target=\"#reporte\"> \r\n");
      out.write("				<i class=\"bi bi-journals fs-4\"></i> \r\n");
      out.write("               	\r\n");
      out.write("               	<span class=\"fs-5 fw-semibold\">Reportes</span>\r\n");
      out.write("			</a>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"collapse\" id=\"reporte\">\r\n");
      out.write("				<ul class=\"ms-3 pb-1 list-unstyled\">\r\n");
      out.write("					<li class=\"nav-item\">\r\n");
      out.write("						<a href=\"ReclamosController?p=1\" class=\"nav-link link-dark\"> \r\n");
      out.write("							<i class=\"bi bi-book fs-4\"></i>\r\n");
      out.write("							\r\n");
      out.write("							<span class=\"fw-semibold\">Reclamos</span>\r\n");
      out.write("						</a>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</li>\r\n");
      out.write("	</ul>\r\n");
      out.write("\r\n");
      out.write("	<!-- USUARIO IMAGEN-->\r\n");
      out.write("	<div class=\"shadow-lg p-1 \" style=\"border-top: 2px solid #FAE6C5;\">\r\n");
      out.write("		<a href=\"#\" class=\"d-flex align-items-center justify-content-center p-2 link-dark text-decoration-none dropdown-toggle\" id=\"dropdownUser3\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("			<img src=\"./img/default_user.png\" alt=\"photo\" style=\"width: 40px; height: 40px; border-radius: 50%;\"> \r\n");
      out.write("			\r\n");
      out.write("			<span class=\"fs-6 fw-semibold mx-2\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ empleado.getNom_Empleado() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("		</a>\r\n");
      out.write("\r\n");
      out.write("		<ul class=\"dropdown-menu dropdown-menu-end\">\r\n");
      out.write("			<li>\r\n");
      out.write("				<a href=\"indexUser.jsp\" class=\"dropdown-item fw-semibold py-2\">Vista Cliente</a>\r\n");
      out.write("			</li>\r\n");
      out.write("			\r\n");
      out.write("			<li>\r\n");
      out.write("				<a href=\"login?type=logout\" class=\"dropdown-item fw-semibold py-2\">Cerrar Sesión</a>\r\n");
      out.write("			</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"d-flex flex-column flex-grow-1 justify-content-center text-center\" style=\"background-color: #FFF6EA;\">\r\n");
      out.write("			<div>			\r\n");
      out.write("				<h1>Bienvenido al Sistema Usuario</h1>\r\n");
      out.write("				\r\n");
      out.write("				<img src=\"./img/makako_burger.png\" alt=\"Logo\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /indexAdmin.jsp(30,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ nomUsuario == null || nomUsuario.getIdTipoUsuario() == 2 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		");
          if (_jspx_meth_c_005fredirect_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          out.write('	');
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fredirect_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:redirect
    org.apache.taglibs.standard.tag.rt.core.RedirectTag _jspx_th_c_005fredirect_005f0 = (org.apache.taglibs.standard.tag.rt.core.RedirectTag) _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.RedirectTag.class);
    boolean _jspx_th_c_005fredirect_005f0_reused = false;
    try {
      _jspx_th_c_005fredirect_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fredirect_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /indexAdmin.jsp(32,2) name = url type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fredirect_005f0.setUrl("indexUser.jsp");
      int _jspx_eval_c_005fredirect_005f0 = _jspx_th_c_005fredirect_005f0.doStartTag();
      if (_jspx_th_c_005fredirect_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.reuse(_jspx_th_c_005fredirect_005f0);
      _jspx_th_c_005fredirect_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fredirect_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fredirect_005f0_reused);
    }
    return false;
  }
}
