/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-01-21 02:58:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("	<link rel=\"icon\" type=\"image/png\" href=\"./img/icono.jpg\" sizes=\"32x32\"/>\r\n");
      out.write("	<title>Inicio de Sesión</title>\r\n");
      out.write("	\r\n");
      out.write("	<!--GOOGLE FONTS - RALEWAY-->\r\n");
      out.write("	<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("	<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("	<link href=\"https://fonts.googleapis.com/css2?family=Chau+Philomene+One&family=Raleway:wght@500&family=Secular+One&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("	\r\n");
      out.write("	<!--BOOTSTRAP CSS-->\r\n");
      out.write("	<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD\" crossorigin=\"anonymous\">\r\n");
      out.write("	\r\n");
      out.write("	<!--BOOTSTRAP ICONS-->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css\">	\r\n");
      out.write("	\r\n");
      out.write("	<!--CUSTOM CSS-->\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"./css/style.css\">\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"./css/sign_in_up_style.css\">\r\n");
      out.write("	\r\n");
      out.write("	<!--SCRIPTS-->\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"d-flex vh-100\">\r\n");
      out.write("		<div class=\"d-none d-md-flex w-50 align-items-center justify-content-center shadow\" style=\"background-color: #FFF6EA;\">\r\n");
      out.write("			<img alt=\"\" src=\"./img/makako_burger.png\">\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"d-flex flex-grow-1 mx-3\">\r\n");
      out.write("			<div class=\"box-data login shadow\">\r\n");
      out.write("				<h2 class=\"text-center\">Inicio de Sesión</h2>\r\n");
      out.write("	\r\n");
      out.write("				<form class=\"login-form needs-validation\" action=\"login\" method=\"POST\">\r\n");
      out.write("					<input class=\"\" type=\"hidden\" name=\"type\" value=\"login\">\r\n");
      out.write("	\r\n");
      out.write("					<div>\r\n");
      out.write("						");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${invalid ? '<p class=\"login-error\">Correo o contraseña incorrecta</p>' : '' }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("	\r\n");
      out.write("						<input class=\"form-control ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${invalid ? 'is-invalid': ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" type=\"text\" id=\"email\" name=\"email\" autocomplete=\"email\" placeholder=\"Email*\">\r\n");
      out.write("						<div id=\"email-invalid\" class=\"text-start invalid-feedback\"></div>\r\n");
      out.write("					</div>\r\n");
      out.write("	\r\n");
      out.write("					<div>\r\n");
      out.write("						<input class=\"form-control ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${invalid ? 'is-invalid': ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" type=\"password\" id=\"password\" name=\"password\" autocomplete=\"current-password\" placeholder=\"Password*\">\r\n");
      out.write("						<div id=\"password-invalid\" class=\"text-start invalid-feedback\"></div>\r\n");
      out.write("					</div>\r\n");
      out.write("	\r\n");
      out.write("					<a class=\"recover-password\">¿Olvidaste tu contraseña?</a> \r\n");
      out.write("					\r\n");
      out.write("					<input class=\"btn btn-primary\" id=\"validate-login\" type=\"submit\" value=\"INGRESAR AL SISTEMA\">\r\n");
      out.write("				</form>\r\n");
      out.write("				\r\n");
      out.write("				<br>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"d-flex flex-wrap justify-content-between\">\r\n");
      out.write("					<label>¿No tienes cuenta?</label>\r\n");
      out.write("					\r\n");
      out.write("					<div>\r\n");
      out.write("						<a href=\"Cliente.jsp\">Registrarse</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<!-- Modal Recuperar Contraseña -->\r\n");
      out.write("	<template id=\"modal-template\">\r\n");
      out.write("		<div class=\"modal fade\" id=\"recover-password\" tabindex=\"-1\" aria-labelledby=\"recover-password-label\" aria-hidden=\"true\">\r\n");
      out.write("			<div class=\"modal-dialog modal-dialog-centered\">\r\n");
      out.write("				<div class=\"modal-content\">\r\n");
      out.write("					<div class=\"modal-header\"></div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"modal-body\"></div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"modal-footer\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</template>\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"module\" src=\"./js/login.js\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
